version: '2'

services:
  exclave-control-center:
    build: ./exclave-control-center
    privileged: true
    labels:
      io.balena.features.balena-api: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.dbus: '1'
  # glider:
  #   build: ./glider
